/// <reference types="vite/client" />

interface ImportMetaEnv {
  VITE_WHITELISTED_ADMIN_EMAILS: string;
  VITE_SUPER_ADMIN_EMAILS?: string;

  VITE_FIREBASE_API_KEY: string;
  VITE_FIREBASE_AUTH_DOMAIN: string;
  VITE_FIREBASE_PROJECT_ID: string;
  VITE_FIREBASE_STORAGE_BUCKET: string;
  VITE_FIREBASE_MESSAGING_SENDER_ID: string;
  VITE_FIREBASE_APP_ID: string;
  VITE_FIREBASE_MEASUREMENT_ID: string;

  VITE_FLUTTERWAVE_API_URL: string;
  VITE_FLUTTERWAVE_PUBLIC_KEY: string;
  VITE_FLUTTERWAVE_SECRET_KEY: string;
  VITE_FLUTTERWAVE_SUBACCOUNT_ID?: string;
}
