/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicNewsletterRouteImport } from './routes/_public/newsletter'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicEventsRouteImport } from './routes/_public/events'
import { Route as PublicContactUsRouteImport } from './routes/_public/contact-us'
import { Route as PublicAboutUsRouteImport } from './routes/_public/about-us'
import { Route as AuthMandateRouteImport } from './routes/_auth/mandate'
import { Route as AuthGalleryRouteImport } from './routes/_auth/gallery'
import { Route as AuthAlumniRouteImport } from './routes/_auth/alumni'
import { Route as PublicRegisterIndexRouteImport } from './routes/_public/register/index'
import { Route as PublicBulletinIndexRouteImport } from './routes/_public/bulletin/index'
import { Route as PublicRegisterReviewRouteImport } from './routes/_public/register/review'
import { Route as PublicRegisterAccountRouteImport } from './routes/_public/register/account'
import { Route as PublicBulletinArticleRouteImport } from './routes/_public/bulletin/$article'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicNewsletterRoute = PublicNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEventsRoute = PublicEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactUsRoute = PublicContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutUsRoute = PublicAboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => PublicRoute,
} as any)
const AuthMandateRoute = AuthMandateRouteImport.update({
  id: '/_auth/mandate',
  path: '/mandate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGalleryRoute = AuthGalleryRouteImport.update({
  id: '/_auth/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAlumniRoute = AuthAlumniRouteImport.update({
  id: '/_auth/alumni',
  path: '/alumni',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterIndexRoute = PublicRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBulletinIndexRoute = PublicBulletinIndexRouteImport.update({
  id: '/bulletin/',
  path: '/bulletin/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterReviewRoute = PublicRegisterReviewRouteImport.update({
  id: '/register/review',
  path: '/register/review',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterAccountRoute = PublicRegisterAccountRouteImport.update({
  id: '/register/account',
  path: '/register/account',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBulletinArticleRoute = PublicBulletinArticleRouteImport.update({
  id: '/bulletin/$article',
  path: '/bulletin/$article',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/alumni': typeof AuthAlumniRoute
  '/gallery': typeof AuthGalleryRoute
  '/mandate': typeof AuthMandateRoute
  '/about-us': typeof PublicAboutUsRoute
  '/contact-us': typeof PublicContactUsRoute
  '/events': typeof PublicEventsRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/newsletter': typeof PublicNewsletterRoute
  '/': typeof PublicIndexRoute
  '/bulletin/$article': typeof PublicBulletinArticleRoute
  '/register/account': typeof PublicRegisterAccountRoute
  '/register/review': typeof PublicRegisterReviewRoute
  '/bulletin': typeof PublicBulletinIndexRoute
  '/register': typeof PublicRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/alumni': typeof AuthAlumniRoute
  '/gallery': typeof AuthGalleryRoute
  '/mandate': typeof AuthMandateRoute
  '/about-us': typeof PublicAboutUsRoute
  '/contact-us': typeof PublicContactUsRoute
  '/events': typeof PublicEventsRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/newsletter': typeof PublicNewsletterRoute
  '/': typeof PublicIndexRoute
  '/bulletin/$article': typeof PublicBulletinArticleRoute
  '/register/account': typeof PublicRegisterAccountRoute
  '/register/review': typeof PublicRegisterReviewRoute
  '/bulletin': typeof PublicBulletinIndexRoute
  '/register': typeof PublicRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/_auth/alumni': typeof AuthAlumniRoute
  '/_auth/gallery': typeof AuthGalleryRoute
  '/_auth/mandate': typeof AuthMandateRoute
  '/_public/about-us': typeof PublicAboutUsRoute
  '/_public/contact-us': typeof PublicContactUsRoute
  '/_public/events': typeof PublicEventsRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/newsletter': typeof PublicNewsletterRoute
  '/_public/': typeof PublicIndexRoute
  '/_public/bulletin/$article': typeof PublicBulletinArticleRoute
  '/_public/register/account': typeof PublicRegisterAccountRoute
  '/_public/register/review': typeof PublicRegisterReviewRoute
  '/_public/bulletin/': typeof PublicBulletinIndexRoute
  '/_public/register/': typeof PublicRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/alumni'
    | '/gallery'
    | '/mandate'
    | '/about-us'
    | '/contact-us'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/newsletter'
    | '/'
    | '/bulletin/$article'
    | '/register/account'
    | '/register/review'
    | '/bulletin'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alumni'
    | '/gallery'
    | '/mandate'
    | '/about-us'
    | '/contact-us'
    | '/events'
    | '/forgot-password'
    | '/login'
    | '/newsletter'
    | '/'
    | '/bulletin/$article'
    | '/register/account'
    | '/register/review'
    | '/bulletin'
    | '/register'
  id:
    | '__root__'
    | '/_public'
    | '/_auth/alumni'
    | '/_auth/gallery'
    | '/_auth/mandate'
    | '/_public/about-us'
    | '/_public/contact-us'
    | '/_public/events'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/newsletter'
    | '/_public/'
    | '/_public/bulletin/$article'
    | '/_public/register/account'
    | '/_public/register/review'
    | '/_public/bulletin/'
    | '/_public/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AuthAlumniRoute: typeof AuthAlumniRoute
  AuthGalleryRoute: typeof AuthGalleryRoute
  AuthMandateRoute: typeof AuthMandateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/newsletter': {
      id: '/_public/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof PublicNewsletterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/events': {
      id: '/_public/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact-us': {
      id: '/_public/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof PublicContactUsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about-us': {
      id: '/_public/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof PublicAboutUsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/mandate': {
      id: '/_auth/mandate'
      path: '/mandate'
      fullPath: '/mandate'
      preLoaderRoute: typeof AuthMandateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/gallery': {
      id: '/_auth/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/alumni': {
      id: '/_auth/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AuthAlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register/': {
      id: '/_public/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/bulletin/': {
      id: '/_public/bulletin/'
      path: '/bulletin'
      fullPath: '/bulletin'
      preLoaderRoute: typeof PublicBulletinIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register/review': {
      id: '/_public/register/review'
      path: '/register/review'
      fullPath: '/register/review'
      preLoaderRoute: typeof PublicRegisterReviewRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register/account': {
      id: '/_public/register/account'
      path: '/register/account'
      fullPath: '/register/account'
      preLoaderRoute: typeof PublicRegisterAccountRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/bulletin/$article': {
      id: '/_public/bulletin/$article'
      path: '/bulletin/$article'
      fullPath: '/bulletin/$article'
      preLoaderRoute: typeof PublicBulletinArticleRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutUsRoute: typeof PublicAboutUsRoute
  PublicContactUsRoute: typeof PublicContactUsRoute
  PublicEventsRoute: typeof PublicEventsRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicNewsletterRoute: typeof PublicNewsletterRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicBulletinArticleRoute: typeof PublicBulletinArticleRoute
  PublicRegisterAccountRoute: typeof PublicRegisterAccountRoute
  PublicRegisterReviewRoute: typeof PublicRegisterReviewRoute
  PublicBulletinIndexRoute: typeof PublicBulletinIndexRoute
  PublicRegisterIndexRoute: typeof PublicRegisterIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutUsRoute: PublicAboutUsRoute,
  PublicContactUsRoute: PublicContactUsRoute,
  PublicEventsRoute: PublicEventsRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicNewsletterRoute: PublicNewsletterRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicBulletinArticleRoute: PublicBulletinArticleRoute,
  PublicRegisterAccountRoute: PublicRegisterAccountRoute,
  PublicRegisterReviewRoute: PublicRegisterReviewRoute,
  PublicBulletinIndexRoute: PublicBulletinIndexRoute,
  PublicRegisterIndexRoute: PublicRegisterIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AuthAlumniRoute: AuthAlumniRoute,
  AuthGalleryRoute: AuthGalleryRoute,
  AuthMandateRoute: AuthMandateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
