/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminMandatesRouteImport } from './routes/admin/mandates'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminArticlesRouteImport } from './routes/admin/articles'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminAlertsRouteImport } from './routes/admin/alerts'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as AuthGalleryRouteImport } from './routes/_auth/gallery'
import { Route as AuthAlumniRouteImport } from './routes/_auth/alumni'
import { Route as PublicRegisterIndexRouteImport } from './routes/_public/register/index'
import { Route as PublicDefaultUserGuideRouteImport } from './routes/_public/_default/user-guide'
import { Route as PublicDefaultNewsletterRouteImport } from './routes/_public/_default/newsletter'
import { Route as PublicDefaultMembershipRouteImport } from './routes/_public/_default/membership'
import { Route as PublicDefaultEventsRouteImport } from './routes/_public/_default/events'
import { Route as PublicDefaultContactUsRouteImport } from './routes/_public/_default/contact-us'
import { Route as PublicDefaultAboutUsRouteImport } from './routes/_public/_default/about-us'
import { Route as AuthMandateLayoutRouteImport } from './routes/_auth/mandate/_layout'
import { Route as PublicDefaultBulletinIndexRouteImport } from './routes/_public/_default/bulletin/index'
import { Route as AuthMandateLayoutIndexRouteImport } from './routes/_auth/mandate/_layout.index'
import { Route as PublicDefaultEventsEventIdRouteImport } from './routes/_public/_default/events/$eventId'
import { Route as PublicDefaultBulletinArticleRouteImport } from './routes/_public/_default/bulletin/$article'
import { Route as AuthMandateLayoutPledgeRouteImport } from './routes/_auth/mandate/_layout.pledge'
import { Route as AuthMandateLayoutDashboardRouteImport } from './routes/_auth/mandate/_layout.dashboard'
import { Route as AuthMandateLayoutCertificateRouteImport } from './routes/_auth/mandate/_layout.certificate'

const AuthMandateRouteImport = createFileRoute('/_auth/mandate')()

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMandateRoute = AuthMandateRouteImport.update({
  id: '/mandate',
  path: '/mandate',
  getParentRoute: () => AuthRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMandatesRoute = AdminMandatesRouteImport.update({
  id: '/mandates',
  path: '/mandates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const AuthGalleryRoute = AuthGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAlumniRoute = AuthAlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => AuthRoute,
} as any)
const PublicRegisterIndexRoute = PublicRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDefaultUserGuideRoute = PublicDefaultUserGuideRouteImport.update({
  id: '/_default/user-guide',
  path: '/user-guide',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDefaultNewsletterRoute = PublicDefaultNewsletterRouteImport.update({
  id: '/_default/newsletter',
  path: '/newsletter',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDefaultMembershipRoute = PublicDefaultMembershipRouteImport.update({
  id: '/_default/membership',
  path: '/membership',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDefaultEventsRoute = PublicDefaultEventsRouteImport.update({
  id: '/_default/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDefaultContactUsRoute = PublicDefaultContactUsRouteImport.update({
  id: '/_default/contact-us',
  path: '/contact-us',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDefaultAboutUsRoute = PublicDefaultAboutUsRouteImport.update({
  id: '/_default/about-us',
  path: '/about-us',
  getParentRoute: () => PublicRoute,
} as any)
const AuthMandateLayoutRoute = AuthMandateLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthMandateRoute,
} as any)
const PublicDefaultBulletinIndexRoute =
  PublicDefaultBulletinIndexRouteImport.update({
    id: '/_default/bulletin/',
    path: '/bulletin/',
    getParentRoute: () => PublicRoute,
  } as any)
const AuthMandateLayoutIndexRoute = AuthMandateLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthMandateLayoutRoute,
} as any)
const PublicDefaultEventsEventIdRoute =
  PublicDefaultEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => PublicDefaultEventsRoute,
  } as any)
const PublicDefaultBulletinArticleRoute =
  PublicDefaultBulletinArticleRouteImport.update({
    id: '/_default/bulletin/$article',
    path: '/bulletin/$article',
    getParentRoute: () => PublicRoute,
  } as any)
const AuthMandateLayoutPledgeRoute = AuthMandateLayoutPledgeRouteImport.update({
  id: '/pledge',
  path: '/pledge',
  getParentRoute: () => AuthMandateLayoutRoute,
} as any)
const AuthMandateLayoutDashboardRoute =
  AuthMandateLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthMandateLayoutRoute,
  } as any)
const AuthMandateLayoutCertificateRoute =
  AuthMandateLayoutCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => AuthMandateLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteWithChildren
  '/alumni': typeof AuthAlumniRoute
  '/gallery': typeof AuthGalleryRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/mandates': typeof AdminMandatesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/mandate': typeof AuthMandateLayoutRouteWithChildren
  '/about-us': typeof PublicDefaultAboutUsRoute
  '/contact-us': typeof PublicDefaultContactUsRoute
  '/events': typeof PublicDefaultEventsRouteWithChildren
  '/membership': typeof PublicDefaultMembershipRoute
  '/newsletter': typeof PublicDefaultNewsletterRoute
  '/user-guide': typeof PublicDefaultUserGuideRoute
  '/register': typeof PublicRegisterIndexRoute
  '/mandate/certificate': typeof AuthMandateLayoutCertificateRoute
  '/mandate/dashboard': typeof AuthMandateLayoutDashboardRoute
  '/mandate/pledge': typeof AuthMandateLayoutPledgeRoute
  '/bulletin/$article': typeof PublicDefaultBulletinArticleRoute
  '/events/$eventId': typeof PublicDefaultEventsEventIdRoute
  '/mandate/': typeof AuthMandateLayoutIndexRoute
  '/bulletin': typeof PublicDefaultBulletinIndexRoute
}
export interface FileRoutesByTo {
  '/alumni': typeof AuthAlumniRoute
  '/gallery': typeof AuthGalleryRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/mandates': typeof AdminMandatesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/mandate': typeof AuthMandateLayoutIndexRoute
  '/about-us': typeof PublicDefaultAboutUsRoute
  '/contact-us': typeof PublicDefaultContactUsRoute
  '/events': typeof PublicDefaultEventsRouteWithChildren
  '/membership': typeof PublicDefaultMembershipRoute
  '/newsletter': typeof PublicDefaultNewsletterRoute
  '/user-guide': typeof PublicDefaultUserGuideRoute
  '/register': typeof PublicRegisterIndexRoute
  '/mandate/certificate': typeof AuthMandateLayoutCertificateRoute
  '/mandate/dashboard': typeof AuthMandateLayoutDashboardRoute
  '/mandate/pledge': typeof AuthMandateLayoutPledgeRoute
  '/bulletin/$article': typeof PublicDefaultBulletinArticleRoute
  '/events/$eventId': typeof PublicDefaultEventsEventIdRoute
  '/bulletin': typeof PublicDefaultBulletinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_auth/alumni': typeof AuthAlumniRoute
  '/_auth/gallery': typeof AuthGalleryRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/mandates': typeof AdminMandatesRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/users': typeof AdminUsersRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_auth/mandate': typeof AuthMandateRouteWithChildren
  '/_auth/mandate/_layout': typeof AuthMandateLayoutRouteWithChildren
  '/_public/_default/about-us': typeof PublicDefaultAboutUsRoute
  '/_public/_default/contact-us': typeof PublicDefaultContactUsRoute
  '/_public/_default/events': typeof PublicDefaultEventsRouteWithChildren
  '/_public/_default/membership': typeof PublicDefaultMembershipRoute
  '/_public/_default/newsletter': typeof PublicDefaultNewsletterRoute
  '/_public/_default/user-guide': typeof PublicDefaultUserGuideRoute
  '/_public/register/': typeof PublicRegisterIndexRoute
  '/_auth/mandate/_layout/certificate': typeof AuthMandateLayoutCertificateRoute
  '/_auth/mandate/_layout/dashboard': typeof AuthMandateLayoutDashboardRoute
  '/_auth/mandate/_layout/pledge': typeof AuthMandateLayoutPledgeRoute
  '/_public/_default/bulletin/$article': typeof PublicDefaultBulletinArticleRoute
  '/_public/_default/events/$eventId': typeof PublicDefaultEventsEventIdRoute
  '/_auth/mandate/_layout/': typeof AuthMandateLayoutIndexRoute
  '/_public/_default/bulletin/': typeof PublicDefaultBulletinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/alumni'
    | '/gallery'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/alerts'
    | '/admin/approvals'
    | '/admin/articles'
    | '/admin/audit-logs'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/mandates'
    | '/admin/roles'
    | '/admin/users'
    | '/'
    | '/admin/'
    | '/mandate'
    | '/about-us'
    | '/contact-us'
    | '/events'
    | '/membership'
    | '/newsletter'
    | '/user-guide'
    | '/register'
    | '/mandate/certificate'
    | '/mandate/dashboard'
    | '/mandate/pledge'
    | '/bulletin/$article'
    | '/events/$eventId'
    | '/mandate/'
    | '/bulletin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alumni'
    | '/gallery'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/admin/alerts'
    | '/admin/approvals'
    | '/admin/articles'
    | '/admin/audit-logs'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/mandates'
    | '/admin/roles'
    | '/admin/users'
    | '/'
    | '/admin'
    | '/mandate'
    | '/about-us'
    | '/contact-us'
    | '/events'
    | '/membership'
    | '/newsletter'
    | '/user-guide'
    | '/register'
    | '/mandate/certificate'
    | '/mandate/dashboard'
    | '/mandate/pledge'
    | '/bulletin/$article'
    | '/events/$eventId'
    | '/bulletin'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/admin'
    | '/_auth/alumni'
    | '/_auth/gallery'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/reset-password'
    | '/admin/alerts'
    | '/admin/approvals'
    | '/admin/articles'
    | '/admin/audit-logs'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/mandates'
    | '/admin/roles'
    | '/admin/users'
    | '/_public/'
    | '/admin/'
    | '/_auth/mandate'
    | '/_auth/mandate/_layout'
    | '/_public/_default/about-us'
    | '/_public/_default/contact-us'
    | '/_public/_default/events'
    | '/_public/_default/membership'
    | '/_public/_default/newsletter'
    | '/_public/_default/user-guide'
    | '/_public/register/'
    | '/_auth/mandate/_layout/certificate'
    | '/_auth/mandate/_layout/dashboard'
    | '/_auth/mandate/_layout/pledge'
    | '/_public/_default/bulletin/$article'
    | '/_public/_default/events/$eventId'
    | '/_auth/mandate/_layout/'
    | '/_public/_default/bulletin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/mandate': {
      id: '/_auth/mandate'
      path: '/mandate'
      fullPath: '/mandate'
      preLoaderRoute: typeof AuthMandateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mandates': {
      id: '/admin/mandates'
      path: '/mandates'
      fullPath: '/admin/mandates'
      preLoaderRoute: typeof AdminMandatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/gallery': {
      id: '/_auth/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthGalleryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/alumni': {
      id: '/_auth/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AuthAlumniRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/register/': {
      id: '/_public/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_default/user-guide': {
      id: '/_public/_default/user-guide'
      path: '/user-guide'
      fullPath: '/user-guide'
      preLoaderRoute: typeof PublicDefaultUserGuideRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_default/newsletter': {
      id: '/_public/_default/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof PublicDefaultNewsletterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_default/membership': {
      id: '/_public/_default/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof PublicDefaultMembershipRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_default/events': {
      id: '/_public/_default/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicDefaultEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_default/contact-us': {
      id: '/_public/_default/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof PublicDefaultContactUsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_default/about-us': {
      id: '/_public/_default/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof PublicDefaultAboutUsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/mandate/_layout': {
      id: '/_auth/mandate/_layout'
      path: '/mandate'
      fullPath: '/mandate'
      preLoaderRoute: typeof AuthMandateLayoutRouteImport
      parentRoute: typeof AuthMandateRoute
    }
    '/_public/_default/bulletin/': {
      id: '/_public/_default/bulletin/'
      path: '/bulletin'
      fullPath: '/bulletin'
      preLoaderRoute: typeof PublicDefaultBulletinIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/mandate/_layout/': {
      id: '/_auth/mandate/_layout/'
      path: '/'
      fullPath: '/mandate/'
      preLoaderRoute: typeof AuthMandateLayoutIndexRouteImport
      parentRoute: typeof AuthMandateLayoutRoute
    }
    '/_public/_default/events/$eventId': {
      id: '/_public/_default/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof PublicDefaultEventsEventIdRouteImport
      parentRoute: typeof PublicDefaultEventsRoute
    }
    '/_public/_default/bulletin/$article': {
      id: '/_public/_default/bulletin/$article'
      path: '/bulletin/$article'
      fullPath: '/bulletin/$article'
      preLoaderRoute: typeof PublicDefaultBulletinArticleRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/mandate/_layout/pledge': {
      id: '/_auth/mandate/_layout/pledge'
      path: '/pledge'
      fullPath: '/mandate/pledge'
      preLoaderRoute: typeof AuthMandateLayoutPledgeRouteImport
      parentRoute: typeof AuthMandateLayoutRoute
    }
    '/_auth/mandate/_layout/dashboard': {
      id: '/_auth/mandate/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/mandate/dashboard'
      preLoaderRoute: typeof AuthMandateLayoutDashboardRouteImport
      parentRoute: typeof AuthMandateLayoutRoute
    }
    '/_auth/mandate/_layout/certificate': {
      id: '/_auth/mandate/_layout/certificate'
      path: '/certificate'
      fullPath: '/mandate/certificate'
      preLoaderRoute: typeof AuthMandateLayoutCertificateRouteImport
      parentRoute: typeof AuthMandateLayoutRoute
    }
  }
}

interface AuthMandateLayoutRouteChildren {
  AuthMandateLayoutCertificateRoute: typeof AuthMandateLayoutCertificateRoute
  AuthMandateLayoutDashboardRoute: typeof AuthMandateLayoutDashboardRoute
  AuthMandateLayoutPledgeRoute: typeof AuthMandateLayoutPledgeRoute
  AuthMandateLayoutIndexRoute: typeof AuthMandateLayoutIndexRoute
}

const AuthMandateLayoutRouteChildren: AuthMandateLayoutRouteChildren = {
  AuthMandateLayoutCertificateRoute: AuthMandateLayoutCertificateRoute,
  AuthMandateLayoutDashboardRoute: AuthMandateLayoutDashboardRoute,
  AuthMandateLayoutPledgeRoute: AuthMandateLayoutPledgeRoute,
  AuthMandateLayoutIndexRoute: AuthMandateLayoutIndexRoute,
}

const AuthMandateLayoutRouteWithChildren =
  AuthMandateLayoutRoute._addFileChildren(AuthMandateLayoutRouteChildren)

interface AuthMandateRouteChildren {
  AuthMandateLayoutRoute: typeof AuthMandateLayoutRouteWithChildren
}

const AuthMandateRouteChildren: AuthMandateRouteChildren = {
  AuthMandateLayoutRoute: AuthMandateLayoutRouteWithChildren,
}

const AuthMandateRouteWithChildren = AuthMandateRoute._addFileChildren(
  AuthMandateRouteChildren,
)

interface AuthRouteChildren {
  AuthAlumniRoute: typeof AuthAlumniRoute
  AuthGalleryRoute: typeof AuthGalleryRoute
  AuthMandateRoute: typeof AuthMandateRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAlumniRoute: AuthAlumniRoute,
  AuthGalleryRoute: AuthGalleryRoute,
  AuthMandateRoute: AuthMandateRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicDefaultEventsRouteChildren {
  PublicDefaultEventsEventIdRoute: typeof PublicDefaultEventsEventIdRoute
}

const PublicDefaultEventsRouteChildren: PublicDefaultEventsRouteChildren = {
  PublicDefaultEventsEventIdRoute: PublicDefaultEventsEventIdRoute,
}

const PublicDefaultEventsRouteWithChildren =
  PublicDefaultEventsRoute._addFileChildren(PublicDefaultEventsRouteChildren)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicDefaultAboutUsRoute: typeof PublicDefaultAboutUsRoute
  PublicDefaultContactUsRoute: typeof PublicDefaultContactUsRoute
  PublicDefaultEventsRoute: typeof PublicDefaultEventsRouteWithChildren
  PublicDefaultMembershipRoute: typeof PublicDefaultMembershipRoute
  PublicDefaultNewsletterRoute: typeof PublicDefaultNewsletterRoute
  PublicDefaultUserGuideRoute: typeof PublicDefaultUserGuideRoute
  PublicRegisterIndexRoute: typeof PublicRegisterIndexRoute
  PublicDefaultBulletinArticleRoute: typeof PublicDefaultBulletinArticleRoute
  PublicDefaultBulletinIndexRoute: typeof PublicDefaultBulletinIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicDefaultAboutUsRoute: PublicDefaultAboutUsRoute,
  PublicDefaultContactUsRoute: PublicDefaultContactUsRoute,
  PublicDefaultEventsRoute: PublicDefaultEventsRouteWithChildren,
  PublicDefaultMembershipRoute: PublicDefaultMembershipRoute,
  PublicDefaultNewsletterRoute: PublicDefaultNewsletterRoute,
  PublicDefaultUserGuideRoute: PublicDefaultUserGuideRoute,
  PublicRegisterIndexRoute: PublicRegisterIndexRoute,
  PublicDefaultBulletinArticleRoute: PublicDefaultBulletinArticleRoute,
  PublicDefaultBulletinIndexRoute: PublicDefaultBulletinIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminMandatesRoute: typeof AdminMandatesRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminArticlesRoute: AdminArticlesRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminMandatesRoute: AdminMandatesRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
