/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as AuthGalleryRouteImport } from './routes/_auth/gallery'
import { Route as AuthAlumniRouteImport } from './routes/_auth/alumni'
import { Route as PublicRegisterIndexRouteImport } from './routes/_public/register/index'
import { Route as AuthMandateIndexRouteImport } from './routes/_auth/mandate/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as PublicRegisterReviewRouteImport } from './routes/_public/register/review'
import { Route as PublicRegisterAccountRouteImport } from './routes/_public/register/account'
import { Route as PublicDefaultNewsletterRouteImport } from './routes/_public/_default/newsletter'
import { Route as PublicDefaultMembershipRouteImport } from './routes/_public/_default/membership'
import { Route as PublicDefaultEventsRouteImport } from './routes/_public/_default/events'
import { Route as PublicDefaultContactUsRouteImport } from './routes/_public/_default/contact-us'
import { Route as PublicDefaultAboutUsRouteImport } from './routes/_public/_default/about-us'
import { Route as AuthMandatePledgeRouteImport } from './routes/_auth/mandate/pledge'
import { Route as AuthMandateDashboardRouteImport } from './routes/_auth/mandate/dashboard'
import { Route as AuthMandateCertificateRouteImport } from './routes/_auth/mandate/certificate'
import { Route as AuthAdminUsersRouteImport } from './routes/_auth/admin/users'
import { Route as AuthAdminGalleryRouteImport } from './routes/_auth/admin/gallery'
import { Route as AuthAdminEventsRouteImport } from './routes/_auth/admin/events'
import { Route as AuthAdminArticlesRouteImport } from './routes/_auth/admin/articles'
import { Route as PublicDefaultBulletinIndexRouteImport } from './routes/_public/_default/bulletin/index'
import { Route as PublicDefaultEventsEventIdRouteImport } from './routes/_public/_default/events/$eventId'
import { Route as PublicDefaultBulletinArticleRouteImport } from './routes/_public/_default/bulletin/$article'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const AuthGalleryRoute = AuthGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAlumniRoute = AuthAlumniRouteImport.update({
  id: '/alumni',
  path: '/alumni',
  getParentRoute: () => AuthRoute,
} as any)
const PublicRegisterIndexRoute = PublicRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => PublicRoute,
} as any)
const AuthMandateIndexRoute = AuthMandateIndexRouteImport.update({
  id: '/mandate/',
  path: '/mandate/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthRoute,
} as any)
const PublicRegisterReviewRoute = PublicRegisterReviewRouteImport.update({
  id: '/register/review',
  path: '/register/review',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterAccountRoute = PublicRegisterAccountRouteImport.update({
  id: '/register/account',
  path: '/register/account',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDefaultNewsletterRoute = PublicDefaultNewsletterRouteImport.update({
  id: '/_default/newsletter',
  path: '/newsletter',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDefaultMembershipRoute = PublicDefaultMembershipRouteImport.update({
  id: '/_default/membership',
  path: '/membership',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDefaultEventsRoute = PublicDefaultEventsRouteImport.update({
  id: '/_default/events',
  path: '/events',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDefaultContactUsRoute = PublicDefaultContactUsRouteImport.update({
  id: '/_default/contact-us',
  path: '/contact-us',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDefaultAboutUsRoute = PublicDefaultAboutUsRouteImport.update({
  id: '/_default/about-us',
  path: '/about-us',
  getParentRoute: () => PublicRoute,
} as any)
const AuthMandatePledgeRoute = AuthMandatePledgeRouteImport.update({
  id: '/mandate/pledge',
  path: '/mandate/pledge',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMandateDashboardRoute = AuthMandateDashboardRouteImport.update({
  id: '/mandate/dashboard',
  path: '/mandate/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMandateCertificateRoute = AuthMandateCertificateRouteImport.update({
  id: '/mandate/certificate',
  path: '/mandate/certificate',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminUsersRoute = AuthAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminGalleryRoute = AuthAdminGalleryRouteImport.update({
  id: '/admin/gallery',
  path: '/admin/gallery',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminEventsRoute = AuthAdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminArticlesRoute = AuthAdminArticlesRouteImport.update({
  id: '/admin/articles',
  path: '/admin/articles',
  getParentRoute: () => AuthRoute,
} as any)
const PublicDefaultBulletinIndexRoute =
  PublicDefaultBulletinIndexRouteImport.update({
    id: '/_default/bulletin/',
    path: '/bulletin/',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicDefaultEventsEventIdRoute =
  PublicDefaultEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => PublicDefaultEventsRoute,
  } as any)
const PublicDefaultBulletinArticleRoute =
  PublicDefaultBulletinArticleRouteImport.update({
    id: '/_default/bulletin/$article',
    path: '/bulletin/$article',
    getParentRoute: () => PublicRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/alumni': typeof AuthAlumniRoute
  '/gallery': typeof AuthGalleryRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/': typeof PublicIndexRoute
  '/admin/articles': typeof AuthAdminArticlesRoute
  '/admin/events': typeof AuthAdminEventsRoute
  '/admin/gallery': typeof AuthAdminGalleryRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/mandate/certificate': typeof AuthMandateCertificateRoute
  '/mandate/dashboard': typeof AuthMandateDashboardRoute
  '/mandate/pledge': typeof AuthMandatePledgeRoute
  '/about-us': typeof PublicDefaultAboutUsRoute
  '/contact-us': typeof PublicDefaultContactUsRoute
  '/events': typeof PublicDefaultEventsRouteWithChildren
  '/membership': typeof PublicDefaultMembershipRoute
  '/newsletter': typeof PublicDefaultNewsletterRoute
  '/register/account': typeof PublicRegisterAccountRoute
  '/register/review': typeof PublicRegisterReviewRoute
  '/admin': typeof AuthAdminIndexRoute
  '/mandate': typeof AuthMandateIndexRoute
  '/register': typeof PublicRegisterIndexRoute
  '/bulletin/$article': typeof PublicDefaultBulletinArticleRoute
  '/events/$eventId': typeof PublicDefaultEventsEventIdRoute
  '/bulletin': typeof PublicDefaultBulletinIndexRoute
}
export interface FileRoutesByTo {
  '/alumni': typeof AuthAlumniRoute
  '/gallery': typeof AuthGalleryRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/': typeof PublicIndexRoute
  '/admin/articles': typeof AuthAdminArticlesRoute
  '/admin/events': typeof AuthAdminEventsRoute
  '/admin/gallery': typeof AuthAdminGalleryRoute
  '/admin/users': typeof AuthAdminUsersRoute
  '/mandate/certificate': typeof AuthMandateCertificateRoute
  '/mandate/dashboard': typeof AuthMandateDashboardRoute
  '/mandate/pledge': typeof AuthMandatePledgeRoute
  '/about-us': typeof PublicDefaultAboutUsRoute
  '/contact-us': typeof PublicDefaultContactUsRoute
  '/events': typeof PublicDefaultEventsRouteWithChildren
  '/membership': typeof PublicDefaultMembershipRoute
  '/newsletter': typeof PublicDefaultNewsletterRoute
  '/register/account': typeof PublicRegisterAccountRoute
  '/register/review': typeof PublicRegisterReviewRoute
  '/admin': typeof AuthAdminIndexRoute
  '/mandate': typeof AuthMandateIndexRoute
  '/register': typeof PublicRegisterIndexRoute
  '/bulletin/$article': typeof PublicDefaultBulletinArticleRoute
  '/events/$eventId': typeof PublicDefaultEventsEventIdRoute
  '/bulletin': typeof PublicDefaultBulletinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/alumni': typeof AuthAlumniRoute
  '/_auth/gallery': typeof AuthGalleryRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/_auth/admin/articles': typeof AuthAdminArticlesRoute
  '/_auth/admin/events': typeof AuthAdminEventsRoute
  '/_auth/admin/gallery': typeof AuthAdminGalleryRoute
  '/_auth/admin/users': typeof AuthAdminUsersRoute
  '/_auth/mandate/certificate': typeof AuthMandateCertificateRoute
  '/_auth/mandate/dashboard': typeof AuthMandateDashboardRoute
  '/_auth/mandate/pledge': typeof AuthMandatePledgeRoute
  '/_public/_default/about-us': typeof PublicDefaultAboutUsRoute
  '/_public/_default/contact-us': typeof PublicDefaultContactUsRoute
  '/_public/_default/events': typeof PublicDefaultEventsRouteWithChildren
  '/_public/_default/membership': typeof PublicDefaultMembershipRoute
  '/_public/_default/newsletter': typeof PublicDefaultNewsletterRoute
  '/_public/register/account': typeof PublicRegisterAccountRoute
  '/_public/register/review': typeof PublicRegisterReviewRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/mandate/': typeof AuthMandateIndexRoute
  '/_public/register/': typeof PublicRegisterIndexRoute
  '/_public/_default/bulletin/$article': typeof PublicDefaultBulletinArticleRoute
  '/_public/_default/events/$eventId': typeof PublicDefaultEventsEventIdRoute
  '/_public/_default/bulletin/': typeof PublicDefaultBulletinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/alumni'
    | '/gallery'
    | '/forgot-password'
    | '/login'
    | '/'
    | '/admin/articles'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/users'
    | '/mandate/certificate'
    | '/mandate/dashboard'
    | '/mandate/pledge'
    | '/about-us'
    | '/contact-us'
    | '/events'
    | '/membership'
    | '/newsletter'
    | '/register/account'
    | '/register/review'
    | '/admin'
    | '/mandate'
    | '/register'
    | '/bulletin/$article'
    | '/events/$eventId'
    | '/bulletin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/alumni'
    | '/gallery'
    | '/forgot-password'
    | '/login'
    | '/'
    | '/admin/articles'
    | '/admin/events'
    | '/admin/gallery'
    | '/admin/users'
    | '/mandate/certificate'
    | '/mandate/dashboard'
    | '/mandate/pledge'
    | '/about-us'
    | '/contact-us'
    | '/events'
    | '/membership'
    | '/newsletter'
    | '/register/account'
    | '/register/review'
    | '/admin'
    | '/mandate'
    | '/register'
    | '/bulletin/$article'
    | '/events/$eventId'
    | '/bulletin'
  id:
    | '__root__'
    | '/_auth'
    | '/_public'
    | '/_auth/alumni'
    | '/_auth/gallery'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/'
    | '/_auth/admin/articles'
    | '/_auth/admin/events'
    | '/_auth/admin/gallery'
    | '/_auth/admin/users'
    | '/_auth/mandate/certificate'
    | '/_auth/mandate/dashboard'
    | '/_auth/mandate/pledge'
    | '/_public/_default/about-us'
    | '/_public/_default/contact-us'
    | '/_public/_default/events'
    | '/_public/_default/membership'
    | '/_public/_default/newsletter'
    | '/_public/register/account'
    | '/_public/register/review'
    | '/_auth/admin/'
    | '/_auth/mandate/'
    | '/_public/register/'
    | '/_public/_default/bulletin/$article'
    | '/_public/_default/events/$eventId'
    | '/_public/_default/bulletin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/gallery': {
      id: '/_auth/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AuthGalleryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/alumni': {
      id: '/_auth/alumni'
      path: '/alumni'
      fullPath: '/alumni'
      preLoaderRoute: typeof AuthAlumniRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/register/': {
      id: '/_public/register/'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/mandate/': {
      id: '/_auth/mandate/'
      path: '/mandate'
      fullPath: '/mandate'
      preLoaderRoute: typeof AuthMandateIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/register/review': {
      id: '/_public/register/review'
      path: '/register/review'
      fullPath: '/register/review'
      preLoaderRoute: typeof PublicRegisterReviewRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register/account': {
      id: '/_public/register/account'
      path: '/register/account'
      fullPath: '/register/account'
      preLoaderRoute: typeof PublicRegisterAccountRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_default/newsletter': {
      id: '/_public/_default/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof PublicDefaultNewsletterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_default/membership': {
      id: '/_public/_default/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof PublicDefaultMembershipRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_default/events': {
      id: '/_public/_default/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof PublicDefaultEventsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_default/contact-us': {
      id: '/_public/_default/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof PublicDefaultContactUsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_default/about-us': {
      id: '/_public/_default/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof PublicDefaultAboutUsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_auth/mandate/pledge': {
      id: '/_auth/mandate/pledge'
      path: '/mandate/pledge'
      fullPath: '/mandate/pledge'
      preLoaderRoute: typeof AuthMandatePledgeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mandate/dashboard': {
      id: '/_auth/mandate/dashboard'
      path: '/mandate/dashboard'
      fullPath: '/mandate/dashboard'
      preLoaderRoute: typeof AuthMandateDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mandate/certificate': {
      id: '/_auth/mandate/certificate'
      path: '/mandate/certificate'
      fullPath: '/mandate/certificate'
      preLoaderRoute: typeof AuthMandateCertificateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/users': {
      id: '/_auth/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthAdminUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/gallery': {
      id: '/_auth/admin/gallery'
      path: '/admin/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AuthAdminGalleryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/events': {
      id: '/_auth/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AuthAdminEventsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin/articles': {
      id: '/_auth/admin/articles'
      path: '/admin/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AuthAdminArticlesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/_default/bulletin/': {
      id: '/_public/_default/bulletin/'
      path: '/bulletin'
      fullPath: '/bulletin'
      preLoaderRoute: typeof PublicDefaultBulletinIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_default/events/$eventId': {
      id: '/_public/_default/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof PublicDefaultEventsEventIdRouteImport
      parentRoute: typeof PublicDefaultEventsRoute
    }
    '/_public/_default/bulletin/$article': {
      id: '/_public/_default/bulletin/$article'
      path: '/bulletin/$article'
      fullPath: '/bulletin/$article'
      preLoaderRoute: typeof PublicDefaultBulletinArticleRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAlumniRoute: typeof AuthAlumniRoute
  AuthGalleryRoute: typeof AuthGalleryRoute
  AuthAdminArticlesRoute: typeof AuthAdminArticlesRoute
  AuthAdminEventsRoute: typeof AuthAdminEventsRoute
  AuthAdminGalleryRoute: typeof AuthAdminGalleryRoute
  AuthAdminUsersRoute: typeof AuthAdminUsersRoute
  AuthMandateCertificateRoute: typeof AuthMandateCertificateRoute
  AuthMandateDashboardRoute: typeof AuthMandateDashboardRoute
  AuthMandatePledgeRoute: typeof AuthMandatePledgeRoute
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
  AuthMandateIndexRoute: typeof AuthMandateIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAlumniRoute: AuthAlumniRoute,
  AuthGalleryRoute: AuthGalleryRoute,
  AuthAdminArticlesRoute: AuthAdminArticlesRoute,
  AuthAdminEventsRoute: AuthAdminEventsRoute,
  AuthAdminGalleryRoute: AuthAdminGalleryRoute,
  AuthAdminUsersRoute: AuthAdminUsersRoute,
  AuthMandateCertificateRoute: AuthMandateCertificateRoute,
  AuthMandateDashboardRoute: AuthMandateDashboardRoute,
  AuthMandatePledgeRoute: AuthMandatePledgeRoute,
  AuthAdminIndexRoute: AuthAdminIndexRoute,
  AuthMandateIndexRoute: AuthMandateIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface PublicDefaultEventsRouteChildren {
  PublicDefaultEventsEventIdRoute: typeof PublicDefaultEventsEventIdRoute
}

const PublicDefaultEventsRouteChildren: PublicDefaultEventsRouteChildren = {
  PublicDefaultEventsEventIdRoute: PublicDefaultEventsEventIdRoute,
}

const PublicDefaultEventsRouteWithChildren =
  PublicDefaultEventsRoute._addFileChildren(PublicDefaultEventsRouteChildren)

interface PublicRouteChildren {
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicDefaultAboutUsRoute: typeof PublicDefaultAboutUsRoute
  PublicDefaultContactUsRoute: typeof PublicDefaultContactUsRoute
  PublicDefaultEventsRoute: typeof PublicDefaultEventsRouteWithChildren
  PublicDefaultMembershipRoute: typeof PublicDefaultMembershipRoute
  PublicDefaultNewsletterRoute: typeof PublicDefaultNewsletterRoute
  PublicRegisterAccountRoute: typeof PublicRegisterAccountRoute
  PublicRegisterReviewRoute: typeof PublicRegisterReviewRoute
  PublicRegisterIndexRoute: typeof PublicRegisterIndexRoute
  PublicDefaultBulletinArticleRoute: typeof PublicDefaultBulletinArticleRoute
  PublicDefaultBulletinIndexRoute: typeof PublicDefaultBulletinIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicDefaultAboutUsRoute: PublicDefaultAboutUsRoute,
  PublicDefaultContactUsRoute: PublicDefaultContactUsRoute,
  PublicDefaultEventsRoute: PublicDefaultEventsRouteWithChildren,
  PublicDefaultMembershipRoute: PublicDefaultMembershipRoute,
  PublicDefaultNewsletterRoute: PublicDefaultNewsletterRoute,
  PublicRegisterAccountRoute: PublicRegisterAccountRoute,
  PublicRegisterReviewRoute: PublicRegisterReviewRoute,
  PublicRegisterIndexRoute: PublicRegisterIndexRoute,
  PublicDefaultBulletinArticleRoute: PublicDefaultBulletinArticleRoute,
  PublicDefaultBulletinIndexRoute: PublicDefaultBulletinIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
